# =================================================================================================
#                                  All Rights Reserved.
# =================================================================================================
# File description:
#       .travis.yml to set up CI
#
# =================================================================================================
#    Date      Name                    Description of Change
# 24-Aug-2021  Wayne Shih              Initial create
# 17-Oct-2021  Wayne Shih              Add codacy
# $HISTORY$
# =================================================================================================

language: python

sudo: enabled

python:
  - "3.6"

services:
  - mysql

# commands to install dependencies
install:
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install django-debug-toolbar
  - pip install coverage
  - pip install codecov

# command to set up environment
before_script:
  - sudo bash ./provision.sh
  - export CODACY_PROJECT_TOKEN=a7b57e9b842647d29d7e144d2a906345

# command to run tests
script:
  - coverage run --source='.' manage.py test && coverage report -m && coverage html && coverage xml

# Push the results back to codecov
after_success:
  - codecov
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml

