# Generated by Django 3.1.3 on 2022-03-31 03:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweets', '0002_tweetphoto'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='tweetphoto',
            index_together={('tweet_id', 'status', 'order'), ('status', 'created_at'), ('user_id', 'created_at'), ('has_deleted', 'deleted_at')},
        ),
    ]
