# =================================================================================================
#                                  All Rights Reserved.
# =================================================================================================
# File description:
#       settings
#
# =================================================================================================
#    Date      Name                    Description of Change
# 05-Aug-2021  Wayne Shih              Initial settings, modify DATABASES and ALLOWED_HOSTS
# 06-Aug-2021  Wayne Shih              Add rest_framework, and pagination
# 07-Aug-2021  Wayne Shih              Add account
# 21-Aug-2021  Wayne Shih              Add django-debug-toolbar
# 05-Sep-2021  Wayne Shih              Add tweets
# 07-Sep-2021  Wayne Shih              Add friendships
# 10-Oct-2021  Wayne Shih              React to pylint checks
# 17-Oct-2021  Wayne Shih              Add newsfeeds
# $HISTORY$
# =================================================================================================

"""
Django settings for twitter project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'u7#94#6$fb7-d9+$oo&^grrvtm7%u30(l*q-fyzwmvoouj7=)_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# <Wayne Shih> 21-Aug-2021
# Add white list, it can be domain name too.
# These are virtual machine's ip in host machine world.
ALLOWED_HOSTS = ['127.0.0.1', '192.168.33.10', 'localhost']

# <Wayne Shih> 21-Aug-2021
# Add host machine's ip in virtual machine to white list.
# These are host machine's ip in host virtual world.
INTERNAL_IPS = ['10.0.2.2', ]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # third party
    'rest_framework',
    # Django-Debug-Toolbar
    'debug_toolbar',

    # project apps
    'accounts',
    'tweets',
    'friendships',
    'newsfeeds'
]

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'twitter.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'twitter.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

# <Wayne Shih> 05-Aug-2021
# Update to our mysql config
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'twitter',
        'HOST': '0.0.0.0',
        'PORT': '3306',
        'USER': 'root',
        'PASSWORD': 'yourpassword',  # 这⾥是⾃⼰下载mysql时候输⼊两次的那个密码
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
